name: Linux

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    paths:
      - '.github/workflows/linux.yml'
      - '.github/actions/**'
      - 'src/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - 'cmake/**'

jobs:
  build:
    name: Build ${{ matrix.arch }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        os: [ubuntu-22.04]
        include:
          - os: ubuntu-22.04
            package: QTalk-x86_64
            host: linux
            arch: linux_gcc_64

    # Runs all steps on bash
    defaults:
      run:
        shell: bash

    env:
      QT_VERSION: 6.8.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 1
          fetch-tags: true

      - name: Initial setup
        uses: ./.github/actions/common

      - name: Install dependencies
        run: |
          chmod a+x ./tools/setup/install_deps_debian.sh
          sudo ./tools/setup/install_deps_debian.sh

      - name: Install Qt for Linux
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: ${{ matrix.host }}
          target: desktop
          arch: ${{ matrix.arch }}
          dir: ${{ runner.temp }}
          # modules: qtdeclarative qtquickcontrols2 qtshadertools qtimageformats qt5compat qtmultimedia
          setup-python: false
          cache: true

      - name: Configure
        working-directory: ${{ runner.temp }}/build
        run: ${{ env.QT_ROOT_DIR }}/bin/qt-cmake -S ${{ github.workspace }} -B . -G "Ninja Multi-Config"
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
              -DQTK_UNITTEST_BUILD=${{ matrix.build_type == 'Debug' && 'ON' || 'OFF' }}

      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build . --target all --config ${{ matrix.build_type }} --parallel

      - name: Verify Executable
        if: matrix.build_type == 'Release'
        working-directory: ${{ runner.temp }}/build/${{ matrix.build_type }}
        run: xvfb-run -a ./QTalk --simple-boot-test

      - name: Run unit tests
        if: matrix.build_type == 'Debug'
        working-directory: ${{ runner.temp }}/build/${{ matrix.build_type }}
        run: xvfb-run -a ./QTalk --unittest
